version: "2"

configs:
  - package: users
    input: openapi/users.yaml
    output: internal/web/users/api.gen.go
    generate:
      - types
      - strict-server
      - spec
    output-options:
      skip-prune: true
    compatibility:
      alias-types: true

  - package: tasks
    input: openapi/tasks.yaml
    output: internal/web/tasks/api.gen.go
    generate:
      - types
      - strict-server
      - spec
    output-options:
      skip-prune: true
    compatibility:
      alias-types: true


